version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.4.6"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Updating system packages..."
      - apt-get update -y
      - apt-get install -y curl unzip
      - echo "Installing Terraform version ${TERRAFORM_VERSION}..."
      - cd /tmp
      - curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform installation completed."

  pre_build:
    commands:
      - echo "Executing terraform init..."
      - terraform init

  build:
    commands:
      - echo "Executing terraform plan..."
      - terraform plan
      - echo "Executing terraform apply..."
      - terraform apply -auto-approve
      - echo "Terraform apply completed. Waiting for 10 minutes before destroy..."
      - sleep 600 # Wait for 10 minutes (600 seconds)

  post_build:
    commands:
      - echo "Executing terraform destroy..."
      - terraform destroy -auto-approve
      - echo "Terraform destroy completed. Build process finished."
